### GET request to example server
GET http://localhost:8080/api/v1/products
###

GET http://localhost:8080/api/v1/products/46b16608-134c-497c-82b8-10962b9c6537
###

DELETE http://localhost:8080/api/v1/products/805298c8-8783-4c5c-82cf-b95dfe65a421
###

DELETE http://localhost:8080/api/v1/products/46b16608-134c-497c-82b8-10962b9c6537
###

POST http://localhost:8080/api/v1/products
Content-Type: application/json

{
  "name": "Macbook Pro",
  "description": "Macbook Pro m4 13 inch",
  "price": 0.1,
  "stockLevel": 1,
  "imageUrl": "http://apple.com/macbook"

}

###
PUT http://localhost:8080/api/v1/products/46b16608-134c-497c-82b8-10962b9c6537
Content-Type: application/json

{
  "name" : "null",
  "price": 0.01
}

###
PUT http://localhost:8080/api/v1/products/5029abae-c5c6-493d-8d61-54f1fc300335
Content-Type: application/json

{
  "price": 0.001,
  "imageUrl": "http://apple.com/macbookM4Pro",
  "stockLevel": 0
}

