spring.application.name=spring-boot
spring.datasource.url=jdbc:postgresql://localhost:5333/
spring.datasource.username=khaidevcode
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Everytime we run the application, wipe the current database, and create the new one
spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
